e-com/ECOM_Project/ECOM_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('EcomApp.urls')),
    path('/search/', include('EcomSearch.urls')),
    path('/cart/', include('EcomCart.urls')),
    path('/credential/', include('EcomCredential.urls'))

]

e-com/ECOM_Project/EcomApp/urls.py
from django.conf.urls.static import static
from django.urls import path
from EcomApp import views
from ECOM_Project import settings

app_name = 'EcomApp'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e-com/ECOM_Project/EcomCart/urls.py
from django.urls import path
from . import views

app_name = 'EcomCart'
urlpatterns = [

    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')

]

e-com/ECOM_Project/EcomCredential/urls.py
from django.urls import path
from EcomCredential import views

app_name = 'EcomCredential'
urlpatterns = [
    path('register/', views.Register, name='register'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout')
]

e-com/ECOM_Project/EcomSearch/urls.py
from django.urls import path
from . import views

app_name = 'EcomSearch'
urlpatterns = [
    path('search/', views.SearchResult, name='SearchResult')
]

e-com/ECOM_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;400;600&family=Unbounded&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">

    <script src="{% static 'js/a076d05399.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}

<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

e-com/ECOM_Project/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Cart Page | Proceed to review your items and place order
{% endblock %}

{% block title %}
   Cart - EcomZone
{% endblock %}

{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">Your Cart Is Empty</h1>
        <br>
        <p class="text-center">
            <a href="{% url 'EcomApp:allProdCat' %}">Continue Shopping</a>
        </p>
    </div>
</div>

{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">Your Shopping Cart</h1>
        <br>
    </div>
</div>

<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

        <table class="table custom_table">
            <thead class="custom_thead">
            <tr>
               <th colspan="6">
                   Cart Items
               </th>
            </tr>
            </thead>

            <tbody>
            {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_absolute_url}}">
                            <img src="{{ cart_item.product.prod_img.url }}" alt="random" class="float-left rounded custom_image">
                        </a>
                    </td>

                    <td class="text-center">
                        {{ cart_item.product.name }}
                        <br>
                        SKU : {{ cart_item.product.id }}
                    </td>

                    <td>Price : {{ cart_item.product.price }}</td>

                    <td>Qty : {{ cart_item.quantity }} x</td>

                    <td>$ : {{ cart_item.sub_total }}</td>

                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'EcomCart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus"></i></a><br><br>
                        &nbsp;<a href="{% url 'EcomCart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus"></i></a><br><br>
                        &nbsp;<a href="{% url 'EcomCart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash"></i></a>
                    </td>

                    {% else %}
                     <td>
                        &nbsp;<a href="{% url 'EcomCart:cart_remove' cart_item.product.id %}" ><i class="fa fa-minus"></i></a><br><br>
                        &nbsp;<a href="{% url 'EcomCart:full_remove' cart_item.product.id %}" ><i class="fa fa-trash"></i></a>
                    </td>
                    {% endif %}
                 </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

        <table class="table custom_table">
            <thead class="custom_thead">
            <tr>
                <th colspan="2">
                    Check Out
                </th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <td colspan="2">
                    Please Review and Verify Your Cart Items  before proceeding with payment

                </td>
            </tr>
            <tr>
                <td>
                    <br>Total Amount : &nbsp;&nbsp;&nbsp;<strong>{{total}} $</strong>
                </td>
            </tr>
            </tbody>
        </table>

        <div class="mx-auto">
            <a href="{% url 'EcomApp:allProdCat' %}" class="btn btn-outline-primary btn-block ">Continue Shopping</a>
            <a href="{% url 'EcomApp:allProdCat' %}" class="btn btn-primary btn-block ">Pay Now</a>
        </div>
    </div>

</div>
{% endif %}

{% endblock %}

e-com/ECOM_Project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:150}}
    {% else %}
        Welcome to EcomZone Where you can buy the things that you imagine
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - EcomZone
    {% else %}
        See Cur Cew Collection - EcomZone
    {% endif %}
{% endblock %}

{% block content %}

{% if category %}
    <div  class="mx-auto" align="center">
        <img class="my_image" src="{{category.cat_img.url}}" alt="{{category.name}}">
    </div><br>

    <div class="container" align="center">
        <h2>{{category.name}}</h2>
        <p>{{category.description}}</p>
    </div>

{% else %}

    <div >
        <img class="my_image" src="{% static 'images/banner.jpeg' %}" >
    </div><br>
    <div class="container">
        <div>
            <h3 class="text-center my-title"><b>Our Products</b></h3>
            <p class="text-justify">
                Enterprise ecommerce is the buying and selling of products to large
                companies or organizations. If a large business sells many different types
                of products or has multiple brand lines and transitions into selling online,
                then it is participating in enterprise ecommerce.
            </p>
        </div>
    </div>
{% endif %}


<div class="container">
    <div class="row mx-auto">

        {% for product in products.object_list %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4" style="padding:10px">
            <div class="card text-center">

                <a href="{{ product.get_url }}">
                    <div>
                        <img src="{{product.prod_img.url}}" height="250px" alt="{{product.name}}">
                    </div>
                </a>

                <div class="card-body">
                    <a href="{{product.get_url}}" style="text-decoration:none;color:black">
                        <div class="card-title" style="margin-top:25px;height:5rem">
                            <h1 style="font-size:20px"><b>{{ product.name }}</b></h1>
                            <p style="font-size:13px">$ : {{ product.price }}</p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>

    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{ pg }}" class="btn btn-light btn-sm
            {% if products.number == pg %} btn-outline-primary {%endif%}">{{ pg }}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

e-com/ECOM_Project/templates/footer.html
  <div align="bottom">
    <div class="navbar my_footer">
      <p class="mx-auto">&copy; All Rights Are Reserved</p>
    </div>
  </div>

e-com/ECOM_Project/templates/header.html
{% load static %}
<!-- Image and text -->
<div >
  <nav class="navbar navbar-dark  bg-gradient shadow" style="background-color:#20164D  ">
    <div class="navbar-brand">
      <div class="row">

      <div class="col-sm-2 d-inline-block" style="margin-bottom:5px">
        <img src="{% static 'images/logo_3.png' %}" width="50" height="50"
           style="margin-left:2px;" alt="">
      </div>

      <div class="col-sm-10" style="margin-top:-6px;">
        <h style="font-size:25px;text-shadow: 1px 1px 5px black;margin-left:7px;">
          <h class="main_head" style="font-size:45px;text-shadow: 2px 1px 5px black"><i>E</i></h>Com<b>Z</b>one</h>
      </div></div>
    </div>
  </nav>
</div>

e-com/ECOM_Project/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div>
<div class="signup-form" style="width:35rem;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Log In</h2>
        <p class="hint-text">If you already have account. Log In</p>

        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>

        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>

        <div class=" form-group ">
            <div class="row">
                <div class="col-sm-6">Doesnt have an account? <br> <a href="{% url 'EcomCredential:register' %}" style="color:blue;">Sign Up</a></div>
                <div class="col-sm-6 " align="right"><button type="submit" class="btn btn-primary ">Log In</button></div>
            </div>
        </div>

        <div class="form-group">
            <div class="text-center" style="color:red;">{% for msg1 in messages %} {{ msg1 }} {% endfor %}</div>
        </div>

    </form>
</div>
</div>

{% endblock %}

e-com/ECOM_Project/templates/navbar.html
<div class="sticky-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
  <div class="container-fluid ">
    <a></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll">

        <li class="nav-item {% if 'EcomApp' in request.path %} active {% endif %}">
          <a class="nav-link" aria-current="page" href="{% url 'EcomApp:allProdCat' %}">Products</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarScrollingDropdown"
             role="button" data-bs-toggle="dropdown" aria-expanded="false">Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>

        {% if item_count > 0 %}
        <div>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'EcomCart:cart_details' %}">
            <span class="badge rounded-pill  bg-primary">
            <i class="fa fa-shopping-cart fa-lg material-icons" style="color:white;"></i>{{item_count}}
            </span>
          </a>
        </li>
        </div>
        {% endif %}
      </ul>

      <div class="d-flex">

        <form class="d-flex" style="padding-right:8px;" action="{% url 'EcomSearch:SearchResult' %}"  method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search"></i></button>
        </form>

        <div class="dropdown" style="margin:auto;">
          <a
            class="dropdown-toggle d-flex align-items-center hidden-arrow"
            href=""
            id="navbarDropdownMenuAvatar"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false">
            {% if user.is_authenticated %}
            <img
                    src="https://i.stack.imgur.com/dr5qp.jpg"
                    class="rounded-circle"
                    height="25"
                    alt="D user"
                    loading="lazy" />
            {% else %}
             <img
                     src="https://as2.ftcdn.net/v2/jpg/02/15/84/43/1000_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg"
                     class="rounded-circle"
                     height="25"
                     alt="D user"
                     loading="lazy" />
            {% endif %}
          </a>

          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
            {% if user.is_authenticated %}
            <li>
              <a class="dropdown-item disabled" style="color:blue;">{{user.username}}</a></li>
            <li>
              <a class="dropdown-item" href="{% url 'EcomCredential:logout' %}">Logout</a></li>
            {% else %}
            <li>
              <a class="dropdown-item" href="{% url 'EcomCredential:login' %}">Sign In</a></li>
            <li>
              <a class="dropdown-item" href="{% url 'EcomCredential:register' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
</div>

e-com/ECOM_Project/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        {{product.description|truncatewords:150}}
{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}} - EcomZone
    {% endif %}
{% endblock %}

{% block content %}

<div>
    <div class="row my_prod_row_class">
        <div class=" mx-auto">
            <p><a style="text-decoration:none" href="{% url 'EcomApp:allProdCat' %}">Home</a>
                | <a style="text-decoration:none" href="{{product.category.get_url}}">{{ product.category }}</a>
                | {{product.name}}
            </p>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-md-12 col-lg-6">
                <div align="center" style="padding-top:40px">
                    <img src="{{product.prod_img.url}}" width="50%" alt="{{product.name}}">
                </div>
            </div>

            <div class="col-md-12 col-sm-12 col-md-12 col-lg-6">
                <div style="padding-top:35px">
                    <h1 class="prod_head">{{product.name}}</h1>
                    <p>$ {{product.price}}</p>
                    <p class="desc_title"><b>Product description</b></p>
                    <p class="text-justify" style="font-size:14px">{{product.description}}</p>
                    {% if product.stock <= 0 %}
                        <p style="color:red">Out of Stock</p>
                    {% else %}
                        <a href="{% url 'EcomCart:add_cart' product.id %}">
                            <button class="btn btn-primary">Add To Cart</button>
                        </a>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

</div>

{% endblock %}

e-com/ECOM_Project/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
<div class="signup-form" style="width:35rem;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Sign Up</h2>
        <p class="hint-text">Create your account. Only takes a minute.</p>

        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-6"><input type="text" class="form-control" name="first_name" placeholder="First Name" required="required"></div>
                <div class="col-sm-6"><input type="text" class="form-control" name="last_name" placeholder="Last Name" required="required"></div>
            </div>
        </div>

        <div class="form-group">
            <input type="email" class="form-control" name="email" placeholder="Email" required="required">
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-6">
                    <input type="password" class="form-control" name="password" placeholder="Password" required="required"></div>
                <div class="col-sm-6">
                    <input type="password" class="form-control" name="password1" placeholder="Confirm Password" required="required"></div>
            </div>
        </div>

        <div class="form-group">
            <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
        </div>

        <div class=" form-group ">
            <div class="row">
                <div class="col-sm-6">Already have an account? <br> <a href="{% url 'EcomCredential:login' %}" style="color:blue;">Sign in</a></div>
                <div class="col-sm-6 " align="right"><button type="submit" class="btn btn-primary ">Register Now</button></div>
            </div>
        </div>

        <div class="form-group">
            <div class="text-center" style="color:red;">{% for msg1 in messages %} {{ msg1 }} {% endfor %}</div>
        </div>



    </form>
</div>
</div>

{% endblock %}

e-com/ECOM_Project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to EcomZone Where you can buy the things that you imagine
{% endblock %}

<link rel="stylesheet" href="{% static 'css/custom.css' %}">

{% block title %}
Search
{% endblock %}

{% block content%}
<div class="search_bg bg-light">
    <p class="text-center">You Have Searched For : <b style="color:blue">"{{query}}"</b></p>
</div>

<div class="container">

    <div class="found_prod">
       <p class="fw-lighter"> Product Found : <b style="color:blue">{{number}}</b></p>
    </div>

    <div class="row mx-auto">

        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4" style="padding:10px">
            <div class="card text-center">

                <a href="{{ product.get_url }}">
                    <div>
                        <img src="{{product.prod_img.url}}" height="250px" alt="{{product.name}}">
                    </div>
                </a>

                <div class="card-body">
                    <a href="{{product.get_url}}" style="text-decoration:none;color:black">
                        <div class="card-title" style="margin-top:25px;height:5rem">
                            <h1 style="font-size:20px"><b>{{ product.name }}</b></h1>
                            <p style="font-size:13px">$ : {{ product.price }}</p>
                        </div>
                    </a>
                </div>

            </div>
        </div>

        {% empty %}
        <div class="row mx-auto">
            <p class="text-center">Zero Result Found</p>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}